# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 733c4ed55cea4d7581eee949bcbef37650f04ed06954e42d377b9a77149c062306c5b64493d7ceb37d3f5e209c480161fdf53333127908a884677c1ed467cd99

test:
  secret_key_base: 84904207f240dc45c70c2f0253224e0690b4483c2013dd66876e5ede9ed1d2af9cd821de12748b8c8462dbcb4b4405c93b9d016670191d7ec7694a8f055b667f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
